name: Orchestrate deployment to Production
run-name: Deploying ${{ github.sha }} to production

on:
  # Uncomment to deploy on push to main branch on push
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: ericgi231-me/webapp-template/.github/workflows/deploy-webapp.yml@main
    with:
      app_name: ${{ vars.APP_NAME || 'webapp-template' }}
      public_port: ${{ vars.PUBLIC_PORT || '8080' }}
      node_env: "production"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}