name: Start Application on Production Server
run-name: Start Application on Production Server

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
        type: string
      frontend_image_name:
        description: 'Name of the frontend image'
        required: true
        type: string
      backend_image_name:
        description: 'Name of the backend image'
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy on prod server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/${{ inputs.app_name }}

            # Pull the latest frontend image from GHCR
            docker pull ${{ inputs.frontend_image_name }}:latest

            # Pull the backend image only if it is provided
            if [ -n "${{ inputs.backend_image_name }}" ]; then
              echo "Pulling backend image..."
              docker pull ${{ inputs.backend_image_name }}:latest
            else
              echo "No backend image specified. Skipping backend image pull."
            fi

            # Stop existing containers
            docker compose down || true

            # Start all services defined in docker-compose.yml
            docker compose up -d