name: Upload Deployment Files to Production Server
run-name: Upload Deployment Files to Production Server

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
        type: string
      public_port:
        description: 'Public port to reach apps router'
        required: true
        type: string
      frontend_image_name:
        description: 'Name of the frontend image'
        required: true
        type: string
      backend_image_name:
        description: 'Name of the backend image'
        required: false
        type: string
      node_env:
        description: 'Node environment'
        required: false
        type: string
        default: 'production'
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true

env:
  DATABASE_NAME: ${{ inputs.app_name }}-db
  DATABASE_USER: ${{ inputs.app_name }}-user
  DATABASE_VOLUME: ${{ inputs.app_name }}-db-volume

jobs:
  upload-deploy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Docker Buildx and Cache
        uses: ./.github/actions/setup-docker-cache
        with:
          app_name: ${{ inputs.app_name }}
          
      - name: Create .env file
        run: |
          cat > .env << EOF
          APP_NAME=${{ inputs.app_name }}
          PUBLIC_PORT=${{ inputs.public_port }}
          FRONTEND_IMAGE_NAME=${{ inputs.FRONTEND_IMAGE_NAME }}
          BACKEND_IMAGE_NAME=${{ inputs.BACKEND_IMAGE_NAME }}
          DATABASE_NAME=${{ env.DATABASE_NAME }}
          DATABASE_USER=${{ env.DATABASE_USER }}
          DATABASE_VOLUME=${{ env.DATABASE_VOLUME }}
          NODE_ENV=${{ inputs.node_env }}
          EOF

      - name: Copy files to prod server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ".env,docker-compose.yml"
          target: "/var/www/${{ inputs.app_name }}/"