name: Validate server connection and port availability
description: Connect to the provided server via SSH and check if the specified port is available
run-name: Validating connection + port

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
        type: string
      public_port:
        description: 'Public port to reach apps router'
        required: true
        type: string
  workflow_call:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
        type: string
      public_port:
        description: 'Public port to reach apps router'
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true

jobs:
  check-port-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Port availability on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "SSH connection successful!"

            # Get all used ports on the server
            ALL_USED_PORTS=$(ss -tulnH | awk '{print $5}' | grep -oE '[0-9]+$' | sort -u)
            echo "Currently used ports on the server:" 
            echo "$ALL_USED_PORTS"

            # Get the current app port from Docker Compose
            CURRENT_APP_PORT=$(docker ps --filter "label=com.docker.compose.project=${{ inputs.app_name }}" --format "{{.Ports}}" | awk -F'->' '/->/ {print $1}' | awk -F':' '{print $NF}')
            echo "Current application port: $CURRENT_APP_PORT"

            # Determine the next step based on port usage
            if echo "$ALL_USED_PORTS" | grep -q "${{ inputs.public_port }}"; then
              if [ "$CURRENT_APP_PORT" = "${{ inputs.public_port }}" ]; then
                echo "Port ${{ inputs.public_port }} is in use by the current application."
              else
                echo "Error: Port ${{ inputs.public_port }} is already in use by another application." >&2
                exit 1
              fi
            else
              echo "Port ${{ inputs.public_port }} is available."
            fi