name: Determine if specified app is reachable directly via public port
description: Connect to the provided server via SSH and check if the specified port is reachable from GitHub Actions

on:
  workflow_dispatch:
    inputs:
      public_port:
        description: 'Public port to reach apps router'
        required: true
        type: string
  workflow_call:
    inputs:
      public_port:
        description: 'Public port to reach apps router'
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true

jobs:
  check-port-reachable:
    runs-on: ubuntu-latest
    steps:
      - name: Check Port Reachability from GitHub Worker
        run: |
          echo "Checking if port ${{ inputs.public_port }} can be reached..."
          if nc -zv ${{ secrets.SERVER_HOST }} ${{ inputs.public_port }}; then
            echo "Port ${{ inputs.public_port }} is reachable."
          else
            echo "Error: Port ${{ inputs.public_port }} is not reachable from the GitHub worker." >&2
          fi